"""Answer text facade for formatting helpers and grounding guards."""

from __future__ import annotations

from play_book_studio.retrieval import SessionContext

from .answer_text_commands import has_sufficient_command_grounding, strip_ungrounded_code_blocks
from .answer_text_formatting import (
    ADJACENT_DUPLICATE_CITATION_RE,
    ACTIONABLE_GUIDE_QUERY_RE,
    ANSWER_CODE_BLOCK_RE,
    ANSWER_HEADER_RE,
    ANSWER_TABLE_BLOCK_RE,
    BARE_COMMAND_ANSWER_RE,
    CITATION_RE,
    GREETING_PREFIXES,
    GUIDE_HEADER_RE,
    INLINE_COMMAND_RE,
    INTRO_OFFTOPIC_SENTENCE_RE,
    NAMESPACE_ADMIN_QUERY_RE,
    REPLICA_COUNT_RE,
    RBAC_CLUSTER_ADMIN_DIFF_RE,
    RBAC_REVOKE_QUERY_RE,
    RBAC_VERIFY_QUERY_RE,
    RBAC_YAML_QUERY_RE,
    STRUCTURED_QUERY_RE,
    TRAILING_CITATIONS_RE,
    WEAK_GUIDE_TAIL_RE,
    ensure_korean_product_terms,
    normalize_answer_markup_blocks,
    normalize_answer_text,
    restore_readable_paragraphs,
    reshape_ops_answer_text,
    shape_beginner_grounded_answer,
    shape_install_overview_answer,
    strip_intro_offtopic_noise,
    strip_structured_key_extra_guidance,
    strip_weak_additional_guidance,
    summarize_session_context,
    trim_productization_noise,
)

__all__ = [
    "ADJACENT_DUPLICATE_CITATION_RE",
    "ACTIONABLE_GUIDE_QUERY_RE",
    "ANSWER_CODE_BLOCK_RE",
    "ANSWER_HEADER_RE",
    "ANSWER_TABLE_BLOCK_RE",
    "BARE_COMMAND_ANSWER_RE",
    "CITATION_RE",
    "GREETING_PREFIXES",
    "GUIDE_HEADER_RE",
    "INLINE_COMMAND_RE",
    "INTRO_OFFTOPIC_SENTENCE_RE",
    "NAMESPACE_ADMIN_QUERY_RE",
    "REPLICA_COUNT_RE",
    "RBAC_CLUSTER_ADMIN_DIFF_RE",
    "RBAC_REVOKE_QUERY_RE",
    "RBAC_VERIFY_QUERY_RE",
    "RBAC_YAML_QUERY_RE",
    "STRUCTURED_QUERY_RE",
    "TRAILING_CITATIONS_RE",
    "WEAK_GUIDE_TAIL_RE",
    "SessionContext",
    "ensure_korean_product_terms",
    "has_sufficient_command_grounding",
    "normalize_answer_markup_blocks",
    "normalize_answer_text",
    "restore_readable_paragraphs",
    "reshape_ops_answer_text",
    "shape_beginner_grounded_answer",
    "shape_install_overview_answer",
    "strip_ungrounded_code_blocks",
    "strip_intro_offtopic_noise",
    "strip_structured_key_extra_guidance",
    "strip_weak_additional_guidance",
    "summarize_session_context",
    "trim_productization_noise",
]
