#!/usr/bin/env bash
set -euo pipefail

OUTPUT_DIR="${1:-./artifacts/phase2-inventory}"
PBS_NAMESPACE="${PBS_NAMESPACE:-pbs-ocpops}"
LIGHTSPEED_NAMESPACE="${LIGHTSPEED_NAMESPACE:-openshift-lightspeed}"
OPENSHIFT_AI_NAMESPACES="${OPENSHIFT_AI_NAMESPACES:-redhat-ods-operator redhat-ods-applications openshift-operators}"

mkdir -p "${OUTPUT_DIR}"

require_cmd() {
  local name="$1"
  if ! command -v "${name}" >/dev/null 2>&1; then
    echo "required command not found: ${name}" >&2
    exit 2
  fi
}

write_cmd() {
  local output_file="$1"
  shift
  {
    printf '# command:'
    printf ' %q' "$@"
    printf '\n'
    "$@"
  } > "${output_file}" 2>&1 || {
    local status=$?
    echo "# command exited with ${status}" >> "${output_file}"
    return 0
  }
}

inventory_namespace() {
  local namespace="$1"
  local target_dir="${OUTPUT_DIR}/namespaces/${namespace}"
  mkdir -p "${target_dir}"

  write_cmd "${target_dir}/namespace.yaml" oc get namespace "${namespace}" -o yaml
  write_cmd "${target_dir}/deployments.yaml" oc get deployments -n "${namespace}" -o yaml
  write_cmd "${target_dir}/services.yaml" oc get services -n "${namespace}" -o yaml
  write_cmd "${target_dir}/routes.yaml" oc get routes -n "${namespace}" -o yaml
  write_cmd "${target_dir}/pods-wide.txt" oc get pods -n "${namespace}" -o wide
  write_cmd "${target_dir}/events.txt" oc get events -n "${namespace}" --sort-by=.lastTimestamp
  write_cmd "${target_dir}/configmaps.yaml" oc get configmaps -n "${namespace}" -o yaml

  # Secret data must not be exported. Capture metadata names/types only.
  write_cmd "${target_dir}/secrets-metadata.txt" oc get secrets -n "${namespace}"
}

require_cmd oc

write_cmd "${OUTPUT_DIR}/cluster-version.yaml" oc get clusterversion -o yaml
write_cmd "${OUTPUT_DIR}/whoami.txt" oc whoami
write_cmd "${OUTPUT_DIR}/whoami-server.txt" oc whoami --show-server
write_cmd "${OUTPUT_DIR}/projects.txt" oc get projects
write_cmd "${OUTPUT_DIR}/clusteroperators.txt" oc get clusteroperators
write_cmd "${OUTPUT_DIR}/nodes-wide.txt" oc get nodes -o wide
write_cmd "${OUTPUT_DIR}/storageclasses.yaml" oc get storageclass -o yaml
write_cmd "${OUTPUT_DIR}/csv-all-namespaces.txt" oc get csv -A
write_cmd "${OUTPUT_DIR}/subscriptions-all-namespaces.txt" oc get subscriptions -A
write_cmd "${OUTPUT_DIR}/installplans-all-namespaces.txt" oc get installplans -A
write_cmd "${OUTPUT_DIR}/operatorgroups-all-namespaces.txt" oc get operatorgroups -A

inventory_namespace "${PBS_NAMESPACE}"
inventory_namespace "${LIGHTSPEED_NAMESPACE}"

for namespace in ${OPENSHIFT_AI_NAMESPACES}; do
  inventory_namespace "${namespace}"
done

cat > "${OUTPUT_DIR}/README.md" <<EOF
# Phase 2 Read-Only Inventory

Generated by \`deploy/sno/scripts/phase2-readonly-inventory.sh\`.

This inventory is read-only and intentionally excludes Secret data. Review the files before any
mutation window. Classify live resources as adopt, replace, remove, or external-owner before applying
repository manifests.
EOF

echo "Read-only inventory written to ${OUTPUT_DIR}"
