"""Read-only MCP tool boundary for PBS.

This module intentionally avoids a runtime MCP dependency. It defines the tool
contract and deterministic local handlers so the later MCP transport can wrap
the same read-only behavior without changing tool semantics.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from play_book_studio.aiops.event_timeline import read_timeline_events


PBS_MCP_TOOL_NAMES = (
    "search_pbs_library",
    "get_pbs_document",
    "list_byok_builds",
    "list_recent_pbs_events",
    "get_cli_session_output",
    "get_yaml_apply_history",
    "get_cluster_snapshot",
    "generate_remediation_plan",
)


@dataclass(frozen=True)
class McpTool:
    name: str
    description: str
    input_schema: dict[str, Any]
    read_only: bool = True


def list_pbs_mcp_tools() -> list[McpTool]:
    return [
        McpTool(
            name="search_pbs_library",
            description="Search BYOK-ready PBS Library Markdown exports by keyword.",
            input_schema={
                "type": "object",
                "properties": {
                    "query": {"type": "string"},
                    "limit": {"type": "integer", "minimum": 1, "maximum": 20},
                },
                "required": ["query"],
            },
        ),
        McpTool(
            name="get_pbs_document",
            description="Read one generated BYOK Markdown document by exported path.",
            input_schema={
                "type": "object",
                "properties": {"path": {"type": "string"}},
                "required": ["path"],
            },
        ),
        McpTool(
            name="list_byok_builds",
            description="List local BYOK dry-run build requests and export manifest entries.",
            input_schema={"type": "object", "properties": {}},
        ),
        McpTool(
            name="list_recent_pbs_events",
            description="List recent PBS CLI, YAML, apply, log, and snapshot events.",
            input_schema={
                "type": "object",
                "properties": {"limit": {"type": "integer", "minimum": 1, "maximum": 100}},
            },
        ),
        McpTool(
            name="get_cli_session_output",
            description="Return recent CLI command/output events for a PBS terminal session.",
            input_schema={
                "type": "object",
                "properties": {
                    "session_id": {"type": "string"},
                    "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                },
            },
        ),
        McpTool(
            name="get_yaml_apply_history",
            description="Return recent YAML apply/action execution history captured by PBS.",
            input_schema={
                "type": "object",
                "properties": {
                    "resource_name": {"type": "string"},
                    "namespace": {"type": "string"},
                    "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                },
            },
        ),
        McpTool(
            name="get_cluster_snapshot",
            description="Return the latest captured resource snapshot for a resource.",
            input_schema={
                "type": "object",
                "properties": {
                    "resource_name": {"type": "string"},
                    "namespace": {"type": "string"},
                },
                "required": ["resource_name"],
            },
        ),
        McpTool(
            name="generate_remediation_plan",
            description="Generate a read-only remediation plan from captured PBS evidence.",
            input_schema={
                "type": "object",
                "properties": {
                    "problem": {"type": "string"},
                    "resource_name": {"type": "string"},
                    "namespace": {"type": "string"},
                },
                "required": ["problem"],
            },
        ),
    ]


def execute_read_only_tool(
    tool_name: str,
    arguments: dict[str, Any] | None = None,
    *,
    root_dir: Path | str = ".",
) -> dict[str, Any]:
    args = arguments or {}
    root = Path(root_dir)
    if tool_name == "search_pbs_library":
        return _search_pbs_library(root, str(args.get("query") or ""), _limit(args.get("limit"), 10))
    if tool_name == "get_pbs_document":
        return _get_pbs_document(root, str(args.get("path") or ""))
    if tool_name == "list_byok_builds":
        return _list_byok_builds(root)
    if tool_name == "list_recent_pbs_events":
        return {"items": read_timeline_events(root, limit=_limit(args.get("limit"), 40))}
    if tool_name == "get_cli_session_output":
        return _filter_events(
            root,
            limit=_limit(args.get("limit"), 40),
            session_id=str(args.get("session_id") or ""),
            event_types={"cli_command", "cli_output", "cli_exit", "cli_error"},
        )
    if tool_name == "get_yaml_apply_history":
        return _filter_events(
            root,
            limit=_limit(args.get("limit"), 40),
            namespace=str(args.get("namespace") or ""),
            resource_name=str(args.get("resource_name") or ""),
            event_types={"yaml_apply", "action_execute"},
        )
    if tool_name == "get_cluster_snapshot":
        return _get_cluster_snapshot(
            root,
            resource_name=str(args.get("resource_name") or ""),
            namespace=str(args.get("namespace") or ""),
        )
    if tool_name == "generate_remediation_plan":
        return _generate_remediation_plan(
            root,
            problem=str(args.get("problem") or ""),
            resource_name=str(args.get("resource_name") or ""),
            namespace=str(args.get("namespace") or ""),
        )
    raise ValueError(f"Unknown PBS MCP tool: {tool_name}")


def _limit(value: Any, default: int) -> int:
    try:
        numeric = int(value)
    except (TypeError, ValueError):
        numeric = default
    return max(1, min(100, numeric))


def _safe_relative_path(root: Path, raw_path: str) -> Path:
    if not raw_path.strip():
        raise ValueError("path is required")
    resolved_root = root.resolve()
    candidate = (root / raw_path).resolve()
    if resolved_root != candidate and resolved_root not in candidate.parents:
        raise ValueError("path escapes PBS workspace root")
    return candidate


def _generated_markdown_files(root: Path) -> list[Path]:
    generated_root = root / "storage" / "byok" / "generated"
    if not generated_root.exists():
        return []
    return sorted(path for path in generated_root.rglob("*.md") if path.is_file())


def _search_pbs_library(root: Path, query: str, limit: int) -> dict[str, Any]:
    terms = [term.lower() for term in query.split() if term.strip()]
    matches: list[dict[str, Any]] = []
    for path in _generated_markdown_files(root):
        text = path.read_text(encoding="utf-8")
        lowered = text.lower()
        if terms and not all(term in lowered for term in terms):
            continue
        matches.append(
            {
                "path": path.relative_to(root).as_posix(),
                "title": _markdown_title(text) or path.stem,
                "preview": text[:500],
            }
        )
        if len(matches) >= limit:
            break
    return {"query": query, "items": matches}


def _get_pbs_document(root: Path, raw_path: str) -> dict[str, Any]:
    path = _safe_relative_path(root, raw_path)
    generated_root = (root / "storage" / "byok" / "generated").resolve()
    if generated_root not in path.resolve().parents and path.resolve() != generated_root:
        raise ValueError("Only generated BYOK Markdown documents are readable through this tool")
    if not path.is_file() or path.suffix.lower() != ".md":
        raise FileNotFoundError(raw_path)
    text = path.read_text(encoding="utf-8")
    return {"path": path.relative_to(root).as_posix(), "title": _markdown_title(text), "content": text}


def _list_byok_builds(root: Path) -> dict[str, Any]:
    manifest_dir = root / "storage" / "byok" / "manifests"
    export_manifest = _read_json_file(manifest_dir / "byok-export-manifest.json", fallback={})
    build_request = _read_json_file(manifest_dir / "byok-build-request.json", fallback={})
    return {
        "export_manifest": export_manifest,
        "build_request": build_request,
        "olsconfig_patch_preview": (manifest_dir / "olsconfig-patch-preview.yaml").as_posix(),
    }


def _filter_events(
    root: Path,
    *,
    limit: int,
    event_types: set[str],
    session_id: str = "",
    namespace: str = "",
    resource_name: str = "",
) -> dict[str, Any]:
    events = []
    for event in read_timeline_events(root, limit=100):
        if event.get("event_type") not in event_types:
            continue
        if session_id and event.get("session_id") != session_id:
            continue
        if namespace and event.get("namespace") != namespace:
            continue
        if resource_name and event.get("resource_name") != resource_name:
            continue
        events.append(event)
        if len(events) >= limit:
            break
    return {"items": events}


def _get_cluster_snapshot(root: Path, *, resource_name: str, namespace: str) -> dict[str, Any]:
    for event in read_timeline_events(root, limit=100):
        if resource_name and event.get("resource_name") != resource_name:
            continue
        if namespace and event.get("namespace") != namespace:
            continue
        snapshot = event.get("resource_snapshot")
        if snapshot:
            return {"resource_snapshot": snapshot, "event": event}
    return {"resource_snapshot": {}, "event": None}


def _generate_remediation_plan(root: Path, *, problem: str, resource_name: str, namespace: str) -> dict[str, Any]:
    related = _filter_events(
        root,
        limit=8,
        event_types={"cli_command", "cli_output", "cli_exit", "cli_error", "yaml_apply", "action_execute"},
        namespace=namespace,
        resource_name=resource_name,
    )["items"]
    lines = [
        f"# Remediation Plan: {problem}",
        "",
        "## Evidence PBS Can Share With Lightspeed",
    ]
    if related:
        for event in related:
            lines.append(f"- {event.get('timestamp', '')}: {event.get('summary', event.get('event_type'))}")
    else:
        lines.append("- No matching PBS events have been captured yet.")
    lines.extend(
        [
            "",
            "## Safe Next Checks",
            "1. Inspect related events for the namespace and resource.",
            "2. Inspect the resource YAML diff before any apply.",
            "3. Confirm rollout, pod phase, logs, and service/route wiring after changes.",
            "",
            "## Mutation Boundary",
            "This MCP tool is read-only and does not apply changes.",
        ]
    )
    return {"plan_markdown": "\n".join(lines), "events": related}


def _read_json_file(path: Path, *, fallback: Any) -> Any:
    if not path.exists():
        return fallback
    return json.loads(path.read_text(encoding="utf-8"))


def _markdown_title(text: str) -> str:
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return ""
