apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-pbs-to-lightspeed-app-server
  namespace: openshift-lightspeed
  labels:
    app.kubernetes.io/name: pbs-lightspeed-ingress
    app.kubernetes.io/part-of: playbookstudio
    pbs.ocpops.io/operator-managed: "true"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: application-server
      app.kubernetes.io/name: lightspeed-service-api
      app.kubernetes.io/part-of: openshift-lightspeed
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: pbs-ocpops
      ports:
        - protocol: TCP
          port: 8443
